[package]
name = "pdb"
version = "0.1.0"
authors = ["Philip Munksgaard <pmunksgaard@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"
anyhow = "1.0.33"
rustyline = "6.3.0"
