WHITESPACE = _{ " " | "\n" }

identifier = { ('a'..'z')+ }

tytuple = { "(" ~ ty ~ ("," ~ ty)+ ~ ","? ~ ")" }

tyident = { 'A'..'Z' ~ ASCII_ALPHANUMERIC* }

ty = { tytuple | tyident }

table = { "table" ~ ty }

int = @{
    "-"?
    ~ (ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
}

bool = { "true" | "false" }

tuple = { "(" ~ expr ~ ("," ~ expr)+ ~ ","? ~ ")" }

expr = { tuple | int | bool }

insert = { "insert" ~ expr }

select = { "select" }

statement = _{ SOI ~ (insert | select) ~ EOI }